local hl_color = require('helpers').hl_color

hl_color('ALEError', 'none', 309)
-- hl_color('ALEErrorLine', 1)
hl_color('ALEErrorSign', 1)
-- hl_color('ALEErrorSignLineNr', 1)
-- hl_color('ALEInfo', 1)
-- hl_color('ALEInfoSign', 1)
-- hl_color('ALEInfoLine', 1)
-- hl_color('ALEInfoSignLineNr', 1)
-- hl_color('ALEStyleError', 1)
-- hl_color('ALEStyleErrorSign', 1)
-- hl_color('ALEStyleErrorSignLineNr', 1)
-- hl_color('ALEStyleWarning', 1)
-- hl_color('ALEStyleWarningSign', 1)
-- hl_color('ALEStyleWarningSignLineNr', 1)
-- hl_color('ALEVirtualTextError', 1)
-- hl_color('ALEVirtualTextInfo', 1)
-- hl_color('ALEVirtualTextStyleError', 1)
-- hl_color('ALEVirtualTextStyleWarning', 1)
-- hl_color('ALEVirtualTextWarning', 1)
-- hl_color('ALEWarning', 1)
-- hl_color('ALEWarningLine', 1)
-- hl_color('ALEWarningSign', 1)
-- hl_color('ALEWarningSignLineNr', 1)
